class Brand {
  static tableName = "BRANDS";
  static migrateStatements = [
    // `
    //   BEGIN
    //     EXECUTE IMMEDIATE 'DROP TABLE BRANDS';
    //   EXCEPTION
    //     WHEN OTHERS THEN NULL;
    //   END;
    // `,
    `
      CREATE TABLE BRANDS (
        id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        name   VARCHAR2(40)
      )
    `
  ];

  static seedStatements = [
    `INSERT INTO BRANDS (name) VALUES ('Brand1')`,
    `INSERT INTO BRANDS (name) VALUES ('Brand2')`,
    `INSERT INTO BRANDS (name) VALUES ('Brand3')`,
    `INSERT INTO BRANDS (name) VALUES ('Brand4')`
  ];
}
export default Brand;
