class Cliente {
  static tableName = "cliente";
  static migrateStatements = [
    `
      CREATE TABLE ${this.tableName} (
        cod         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        nombre        VARCHAR2(40)
      )
    `,
  ];

  static seedStatements = [
    `INSERT INTO ${this.tableName} (nombre) VALUES ('Cliente1')`,
    `INSERT INTO ${this.tableName} (nombre) VALUES ('Cliente2')`,
    `INSERT INTO ${this.tableName} (nombre) VALUES ('Cliente3')`,
    `INSERT INTO ${this.tableName} (nombre) VALUES ('Cliente4')`
  ];
}

export default Cliente;
