class Presupuesto {
  static tableName = "presupuesto";
  static migrateStatements = [
    `
      CREATE TABLE ${this.tableName} (
        cod         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        cod_proyecto   NUMBER,
        fecha DATE,
        FOREIGN KEY (cod_proyecto) REFERENCES proyecto(cod)
      )
    `,
  ];

  static seedStatements = [
    `INSERT INTO ${this.tableName} (cod_proyecto, fecha) VALUES (1, TO_DATE('2021-10-01', 'YYYY-MM-DD'))`,
    `INSERT INTO ${this.tableName} (cod_proyecto, fecha) VALUES (1, TO_DATE('2021-10-02', 'YYYY-MM-DD'))`,
    `INSERT INTO ${this.tableName} (cod_proyecto, fecha) VALUES (1, TO_DATE('2021-10-03', 'YYYY-MM-DD'))`,
    `INSERT INTO ${this.tableName} (cod_proyecto, fecha) VALUES (1, TO_DATE('2021-10-04', 'YYYY-MM-DD'))`
  ];
}

export default Presupuesto;
