

class Product {
  static tableName = "PRODUCTS";
  static migrateStatements = [
    // `
    //   BEGIN
    //     EXECUTE IMMEDIATE 'DROP TABLE PRODUCTS';
    //   EXCEPTION
    //     WHEN OTHERS THEN NULL;
    //   END;
    // `,
    `
      CREATE TABLE PRODUCTS (
        id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        name        VARCHAR2(40),
        brand_id    NUMBER,
        category_id VARCHAR2(25),
        price       NUMBER,
        FOREIGN KEY (brand_id) REFERENCES BRANDS(id)
      )
    `,
  ];

  static seedStatements = [
    `INSERT INTO PRODUCTS (name, brand_id, category_id, price) VALUES ('Milk', 1, 'Category1', 100)`,
    `INSERT INTO PRODUCTS (name, brand_id, category_id, price) VALUES ('Banana', 2, 'Category2', 150)`,
    `INSERT INTO PRODUCTS (name, brand_id, category_id, price) VALUES ('Crackers', 3, 'Category3', 200)`,
    `INSERT INTO PRODUCTS (name, brand_id, category_id, price) VALUES ('Bread', 4, 'Category4', 250)`
  ];
}

export default Product;
