class Proyecto {
  static tableName = "proyecto";
  static migrateStatements = [
    `
      CREATE TABLE ${this.tableName} (
        cod         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        nombre        VARCHAR2(40),
        cod_cliente   NUMBER,
        ubigeo VARCHAR2(25),
        FOREIGN KEY (cod_cliente) REFERENCES cliente(cod)
      )
    `,
  ];

  static seedStatements = [
    `INSERT INTO ${this.tableName} (nombre, cod_cliente, ubigeo) VALUES ('Proyecto1', 1, 'Ubigeo1')`,
    `INSERT INTO ${this.tableName} (nombre, cod_cliente, ubigeo) VALUES ('Proyecto2', 1, 'Ubigeo2')`,
    `INSERT INTO ${this.tableName} (nombre, cod_cliente, ubigeo) VALUES ('Proyecto3', 1, 'Ubigeo3')`,
    `INSERT INTO ${this.tableName} (nombre, cod_cliente, ubigeo) VALUES ('Proyecto4', 1, 'Ubigeo4')`
  ];
}

export default Proyecto;
